site_name: My test CI\CD for Documentations

nav:
  - Главная: index.md
  - Документация:
    - Глава 1: glossary.md
    - Глава 2: general_info.md  
    - Глава 3: goals.md
    - Глава 4: object_param.md
    - Глава 5: business_processes.md  
    - Глава 6: system_requirements.md
    - Глава 7: information_model.md
    - Глава 8: component_architecture.md 
    - Глава 9: iIntegration _interaction.md
    - Глава 10: user_interface.md
    - Глава 11: api.md
    - Глава 12: dev_assignments.md
  - Ресурсы:
    - Диаграммы: diagrams/
    - Файрфреймы: wf/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
   - swagger-ui-tag
   - mermaid2