site_name: Приложение для заказа и система оповещения

nav:
  - Главная: index.md
  - Документация:
    - Глава 1 Глоссарий: 1_glossary.md
    - Глава 2 Общие сведения: 2_general_info.md
    - Глава 3 Назначение и цели: 3_goals.md
    - Глава 4 Характеристика объекта: 4_object_param.md
    - Глава 5 Описание бизнес-процессов: 5_business_processes.md
    - Глава 6 Требования к системе: 6_system_requirements.md
    - Глава 7 Информационная модель: 7_information_model.md
    - Глава 8 Компонентная архитектура: 8_сomponent_architecture.md
    - Глава 9 Интеграционное взаимодействие: 9_integration_interaction.md
    - Глава 10 Пользовательский интерфейс: 10_user_interface.md
    - Глава 11 API приложения: 11_api.md
    - Глава 12 Постановки на разработку: 12_dev_assignments.md
    - Глава 13 Тестовые сценарии: 13_test_scenarios.md
  - Ресурсы:
    - Диаграммы: diagrams/index.md
    - Файрфреймы: wf/index.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: ru
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: plantuml
          class: plantuml
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
   - search
   - swagger-ui-tag
   - mermaid2