site_name: Приложение для заказа и система оповещения

nav:
  - Главная: index.md
  - Документация:
    - Глава 1: 1_glossary.md
    - Глава 2: 2_general_info.md
    - Глава 3: 3_goals.md
    - Глава 4: 4_object_param.md
    - Глава 5: 5_business_processes.md
    - Глава 6: 6_system_requirements.md
    - Глава 7: 7_information_model.md
    - Глава 8: 8_сomponent_architecture.md
    - Глава 9: 9_integration_interaction.md
    - Глава 10: 10_user_interface.md
    - Глава 11: 11_api.md
    - Глава 12: 12_dev_assignments.md
  - Ресурсы:
    - Диаграммы: diagrams/index.md
    - Файрфреймы: wf/index.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: ru
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: plantuml
          class: plantuml
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
   - search
   - swagger-ui-tag
   - mermaid2