@startuml Модель предметной области

Entity Клиент
{
Телефон
Участник_бонусной_программы
Пароль
}

Entity Бонусный_счет
{
Тип_бонусов
Баланс
Срок_годности
}

Entity Меню {
Название
Тип
Дата_начала
Дата_окончания
Активно
}

Entity Категория_товара {
Название
Описание
}

Entity Товар {
Название
Тип
Б
Ж
У
Калорийность
Описание
Фото
Цена
Доступность
}

Entity Технологическая_карта {
Название
Описание
XML_данные
Версия
Актуальна
}

Entity Ингредиент {
Название
Б
Ж
У
Калорийность
URL_изображения
Цена_за_единицу
Обязательность
Максимальное_количество
Доступность
}

Entity Комбобургер {
Название
Описание
Наценка
Минимальное_количество_ингредиентов
Максимальное_количество_ингредиентов
Доступность
}

Entity Корзина {
Общая_стоимость
Создание
Состав
Количество
}

Entity Заказ {
Номер_заказа
Статус
Дата_создания
Время_получения
Способ_получения
Способ_оплаты
Итоговая_сумма
Сумма_к_оплате
Использовано_бонусов
}

Entity Чек {
Дата_оплаты
Данные_чека
Статус_оплаты
}

Entity Акция {
Название
Описание
Тип
Значение
Условие
Дата_начала
Дата_окончания
Активно
}

Entity Робот {
Название
Статус
Последнее_известное_состояние
}

Entity Задание_на_производство {
Статус
Приоритет
Время_постановки
Время_начала
Время_окончания
}

Entity Сотрудник {
Имя
Фамилия
Роль
Логин
Пароль
Телефон
}

Entity Журнал_событий {
Уровень
Сообщение
Данные
Метка_времени
}

' Связи
Клиент "1" --> "0..*" Бонусный_счет : имеет 
Клиент "1" --> "1" Корзина : формирует 
Клиент "1" --> "0..*" Заказ : создает 

Меню "1" --> "1..*" Товар : включает 
Меню "1" --> "0..*" Акция : содержит
Категория_товара "1" --> "0..*" Товар : классифицирует 

Заказ "1" --> "1" Чек : генерирует 

Комбобургер --|> Товар

Товар "1..*" -- "0..*" Товар
Товар "1..*" --o "0..*" Корзина : добавляется в
Ингредиент "1..*" -- "0..*" Ингредиент : может заменять

Товар --> Технологическая_карта : использует карту

Заказ "1" --> "1" Задание_на_производство : запускает
Робот "1" --> "0..*" Задание_на_производство : выполняет

Сотрудник "1" --> "0..*" Заказ : обрабатывает возврат
Сотрудник "1" --> "0..*" Журнал_событий : инициирует

Акция ..> Товар : применяется к

@enduml