@startuml

left to right direction

actor "Посетитель" as Guest
actor "Менеджер на гостеприимстве" as HospitalityManager
actor "Менеджер по ассортименту" as AssortmentManager
actor "Менеджеры на производстве" as ProductionSystem

rectangle "Система ресторана" {
    usecase "Оформить заказ" as UC_PlaceOrder 
    usecase "Просмотреть меню" as UC_ViewMenu
    usecase "Добавить позиции в корзину" as UC_AddToCart
    usecase "Произвести оплату" as UC_MakePayment
    usecase "Получить талон с номером" as UC_GetReceipt
    usecase "Проверить программу лояльности" as UC_CheckLoyalty
    usecase "Зарегистрироваться в программе" as UC_RegisterLoyalty
    usecase "Использовать бонусные баллы" as UC_UseLoyaltyPoints
    usecase "Применить скидку бизнес-ланч" as UC_ApplyBusinessLunchDiscount
    usecase "Добавить подарок" as UC_ApplyFreeGift

    usecase "Обработать возврат денег" as UC_ProcessRefund 
    usecase "Возврат наличными" as UC_CashRefund
    usecase "Возврат на карту" as UC_CardRefund
  
    usecase "Управление меню и акциями" as UC_ManageMenu 
    usecase "Добавить новую позицию" as UC_AddMenuItem
    usecase "Изменить цену" as UC_ChangePrice
    usecase "Настроить акции" as UC_SetupPromotions
  
    usecase "Настроить технологические карты" as UC_ConfigureRecipes
    usecase "Мониторинг производства" as UC_MonitorProduction
    usecase "Оповестить о готовности заказа" as UC_NotifyOrderReady

    ' Include-связи (обязательные шаги)
    UC_PlaceOrder ..> UC_ViewMenu : include
    UC_PlaceOrder ..> UC_AddToCart : include
    UC_PlaceOrder ..> UC_MakePayment : include
    UC_PlaceOrder ..> UC_GetReceipt : include
    UC_PlaceOrder ..> UC_CheckLoyalty : include

    UC_ProcessRefund <|.. UC_CashRefund 
    UC_ProcessRefund <|.. UC_CardRefund 

    UC_ManageMenu ..> UC_AddMenuItem : include
    UC_ManageMenu ..> UC_ChangePrice : include
    UC_ManageMenu ..> UC_SetupPromotions : include

    ' Extend-связи (условные/дополнительные шаги)
    UC_CheckLoyalty <.. UC_RegisterLoyalty : extends
    UC_CheckLoyalty <.. UC_UseLoyaltyPoints : extends
    UC_MakePayment <.. UC_ApplyBusinessLunchDiscount : extends
    UC_MakePayment <.. UC_ApplyFreeGift : extends
}

' Связи акторов с Use Case
Guest --> UC_PlaceOrder
Guest --> UC_ViewMenu
Guest --> UC_RegisterLoyalty

HospitalityManager --> UC_ProcessRefund
HospitalityManager --> UC_NotifyOrderReady

AssortmentManager --> UC_ManageMenu
AssortmentManager --> UC_ConfigureRecipes

ProductionSystem --> UC_MonitorProduction
ProductionSystem --> UC_NotifyOrderReady

@enduml